version: '3.8'

services:
  # Book Catalog Service
  book_catalog:
    build:
      context: ./book_catalog
      dockerfile: Dockerfile
    container_name: book_catalog
    ports:
      - "8000:8000"
    environment:
      - PORT=8000
      - DATABASE_URL=postgresql://dastask7_user:uGT2aMJmlvbjQCLbajsOYwKTG1B97l0e@dpg-crul5c3tq21c738kod50-a.singapore-postgres.render.com/dastask7?sslmode=disable
    restart: always

  # Inventory Management Service
  inventory_management:
    build:
      context: ./inventory_management
      dockerfile: Dockerfile
    container_name: inventory_management
    ports:
      - "8001:8001"
    environment:
      - PORT=8001
      - DATABASE_URL=postgresql://dastask7_user:uGT2aMJmlvbjQCLbajsOYwKTG1B97l0e@dpg-crul5c3tq21c738kod50-a.singapore-postgres.render.com/dastask7?sslmode=disable
    restart: always
